version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    # No need for depends_on since we are not using a separate db service

# No volumes section needed since SQLite is file-based and will be stored in the mounted volume